FROM flink:{{ flink_version }}

# install python3: it has updated Python to 3.9 in Debian 11 and so install Python 3.7 from source, \
# it currently only supports Python 3.6, 3.7 and 3.8 in PyFlink officially.

ARG PYTHON_VERSION={{ python_version }}
# install python3: it has updated Python to 3.9 in Debian 11 and so install Python 3.7 from source, \
# it currently only supports Python 3.6, 3.7 and 3.8 in PyFlink officially.

RUN apt-get update -y && \
  apt-get install -y git build-essential libssl-dev zlib1g-dev libbz2-dev libffi-dev && \
  wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz && \
  tar -xvf Python-${PYTHON_VERSION}.tgz && \
  cd Python-${PYTHON_VERSION} && \
  ./configure --without-tests --enable-shared && \
  make -j6 && \
  make install && \
  ldconfig /usr/local/lib && \
  cd .. && rm -f Python-${PYTHON_VERSION}.tgz && rm -rf Python-${PYTHON_VERSION} && \
  ln -s /usr/local/bin/python3 /usr/local/bin/python && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

## install PyFlink
#RUN pip3 install apache-flink=={{ flink_version }}

USER flink
{% if enable_flink_sql %} ## Adding SQL Scripts
RUN mkdir /opt/flink/usrlib
ADD target/flink-sql-runner-example-*.jar /opt/flink/usrlib/sql-runner.jar
ADD sql /opt/flink/usrlib/sql
{%endif%}
## Adding Flink Scripts
#RUN mkdir /opt/flink/usrlib
#ADD py_ml.py /opt/flink/usrlib/py_ml.py


